### PR TITLE
develop

### PR DESCRIPTION
**Pull request by maciej-kluczny-sabre**
Fixing issue CDAP-12187 by using cdap-common code to extract binary payload from java nio's ByteBuffer Cask Ops 7/25/17 9:40 AM

### CODE REVIEW

**Review by nitinmotgi — APPROVED** [review]
LGTM

**Comment by nitinmotgi** [comment]
Seems like the build is failing

**Comment by maciej-kluczny-sabre** [comment]
Can you provide more information? I'm new to travis-ci but afaik it complains about JAVA_HOME parameter.

**Comment by russorat** [comment]
Builds fine locally on my machine.
[kafka-plugins-build.txt](https://github.com/hydrator/kafka-plugins/files/1174768/kafka-plugins-build.txt)

**Comment by sreevatsanraman** [comment]
Created a JIRA to investigate Travis build https://issues.cask.co/browse/CDAP-12192

**Pull request merged**
