### PR TITLE
Bumps version to 2.2.1

### PR DESCRIPTION
**Pull request by ajainarayanan**

### CODE REVIEW

**Review by albertshau — COMMENTED** [review]
other snapshot versions should also be removed in the top level pom

**Comment by albertshau** [comment]
also, parent version range needs to be updated with the lower version equal to the CDAP version being used in this repo

**Comment by ajainarayanan** [comment]
@albertshau I didn't update the cdap version and the parent artifact version yet because it caused problems last time we did that. Once we bumped the version to 6.1.1 and when people were building the plugin in local the build started failing as we didn't push the artifacts in maven central yet ([original PR](https://github.com/data-integrations/kafka-plugins/pull/71) and the [revert](https://github.com/data-integrations/kafka-plugins/pull/72)). 
Thought I will open a separate PR once the cdap artifacts are pushed to maven central. Let me know if that is not the right approach. I can add the changes to the same branch.

**Review by albertshau — COMMENTED** [review]
update version range as well

**Review by albertshau — APPROVED** [review]

**Pull request merged**
