### PR TITLE
Feature release/make offset table name unique

### PR DESCRIPTION
**Pull request by yaojiefeng**

### CODE REVIEW

**Review by nitinmotgi — CHANGES_REQUESTED** [review]
Why can't we use one table. This is not scalable. If we have 100 pipelines with Kafka, we would have 100 tables with one row each -- is this necessary. Why can't there be a row in each table.

**Comment by yaojiefeng** [comment]
@nitinmotgi This pr is doing what you mentioned. It will use a table called "__kafka_batch_source_offsets" for all kafka pipelines. The property of offset table name is optional now.

**Comment by bdmogal** [comment]
@yaojiefeng @nitinmotgi I updated the description in the last two comments. Please verify. If it LGTY, @yaojiefeng can you squash+ merge?

**Comment by nitinmotgi** [comment]
LGTM 👍

**Comment by yaojiefeng** [comment]
LGTM, merging

**Pull request merged**
